url: http://www.disarm.io
baseurl:

# Site settings
title: DiSARM
email: hello@disarm.io
description: "Data-driven decision making platform for malaria"
host: 0.0.0.0

image_root_url: https://res.cloudinary.com/disarm/image/upload/
image_account : disarm-website

collections:
  team_members:
    output: true
  partners:
    output: true
  support_partners:
    output: true
  progress_updates:
    output: true

# Build settings
markdown: kramdown
permalink: pretty

prose:
  metadata:
    _team_members:
      - name: name
        field:
          label: Team member name
          element: text
          type: text
      - name: role
        field:
          label: Role
          element: text
          type: text
      - name: image
        field:
          label: Cloudinary image ID
          element: text
          type: text
    _progress_updates:
      - name: title # Automated risk modelling is working
        field:
          label: Update title
          element: text
          type: text
      - name: layout # post
        field:
          element: hidden
          value: post
      - name: post_date # '2016-11-03'
        field:
          label: Date of post
          element: text
          type: date
      - name: image # Outline_Of_IRS_Work
        field:
          label: Cloudinary image ID
          element: text
          type: text
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
